version: '3.8'

services:
  seq:
    image: datalust/seq:2024.3
    container_name: compre_app_seq
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_DISABLE_FIRSTUSER=True
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: compre_app_sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=P@ssw0rd123
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - backend
      
  redis:
    image: redis
    container_name: compre_app_redis
    command: redis-server --requirepass P@ssw0rd123
    ports:
      - "6379:6379"
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compre_app_api
    environment:
      ConnectionStrings__SqlServerConnection: "Server=sqlserver,1433;Database=CompreAppDb2;User Id=sa;Password=P@ssw0rd123;TrustServerCertificate=True"
      ConnectionStrings__RedisConnection: "redis:6379,password=P@ssw0rd123"
      ConnectionStrings__SeqConnection: "http://seq:5341"
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "5010:8080"
    depends_on:
      - sqlserver
      - seq
      - redis
    networks:
      - backend

volumes:
  seq-data:
  sqlserver-data:

networks:
  backend:
    driver: bridge